In [1]:
import tensorflow as tf

In [2]:
print ("TF Version: ", tf.__version__)

TF Version:  2.12.0


In [3]:
print ("Eager execution: ", tf.executing_eagerly())

Eager execution:  True


In [4]:
x = tf.constant(5, name='x')
y = tf.constant(8, name='y')

@tf.function
def calc_prod(x,y):
    z = 2*x + 3*y
    return z

result = calc_prod(x,y)
print('result = ',result)

result =  tf.Tensor(34, shape=(), dtype=int32)


#### @tf.function
This function makes inherit functions 'seems' like regular pyhton functions

In [5]:
### Generate a normalized tensor
normal1 = tf.Variable(tf.random.normal([2,3,4]), dtype=tf.float32)
normal1

<tf.Variable 'Variable:0' shape=(2, 3, 4) dtype=float32, numpy=
array([[[-0.00246354, -0.19502442,  0.7879207 ,  2.1441026 ],
        [-0.39013222, -0.12530161, -0.55748326, -0.53423554],
        [ 0.4365988 , -0.67371494, -0.19191936, -0.7846794 ]],

       [[ 1.3869767 ,  1.1920148 , -0.8503473 ,  0.9046559 ],
        [ 0.53607774,  1.5569589 , -1.0865768 ,  1.8166689 ],
        [ 0.8565215 ,  0.6111339 , -1.0073297 ,  1.1437734 ]]],
      dtype=float32)>

In [6]:
tf.rank(normal1)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [7]:
tf.shape(normal1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4])>

In [8]:
normal2 = tf.random.normal([2,3,4], dtype=tf.float32)
normal2

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[-0.7262466 ,  1.143045  , -0.0604397 ,  1.6947546 ],
        [ 0.5179211 ,  1.5084895 , -0.20093483, -0.1912706 ],
        [ 0.50448155, -0.11771435, -0.52633214, -1.8295678 ]],

       [[ 2.139276  , -0.43917784, -1.3938938 ,  0.21544221],
        [-0.7357928 ,  0.97663164, -1.5967041 , -1.6007953 ],
        [-0.83573896,  0.82877314, -0.95790327, -1.3456662 ]]],
      dtype=float32)>

In [9]:
normal2.ndim

3

In [10]:
tf.shape(normal2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4])>

In [13]:
a = tf.add(4,2)

@tf.function
def compute_values():
    print(a) # 6

compute_values()

tf.Tensor(6, shape=(), dtype=int32)


In [14]:
# if we put the operation tf.add inside @tf.function we don´t get the result, but we get types and attributes

@tf.function
def compute_values():
    a = tf.add(4,2)
    print(a) # 6

compute_values()

Tensor("Add:0", shape=(), dtype=int32)


In [18]:
#Another way to get the result when the operation is inside the @tf.function
@tf.function
def compute_values():
    a = tf.add(4,2)
    return a

result = compute_values()
print("Result: ",result)

Result:  tf.Tensor(6, shape=(), dtype=int32)


In [19]:
# A third solution is to cast the numerc values to Tensors
@tf.function
def compute_values():
    a = tf.add(tf.constant(4),tf.constant(2))
    return a

result = compute_values()
print("Result: ",result)

Result:  tf.Tensor(6, shape=(), dtype=int32)
