In [1]:
import tensorflow as tf

In [2]:
print ("TF Version: ", tf.__version__)

TF Version:  2.12.0


In [3]:
print ("Eager execution: ", tf.executing_eagerly())

Eager execution:  True


In [4]:
x = tf.constant(5, name='x')
y = tf.constant(8, name='y')

@tf.function
def calc_prod(x,y):
    z = 2*x + 3*y
    return z

result = calc_prod(x,y)
print('result = ',result)

result =  tf.Tensor(34, shape=(), dtype=int32)


#### @tf.function
This function makes inherit functions 'seems' like regular pyhton functions

In [5]:
### Generate a normalized tensor
normal1 = tf.Variable(tf.random.normal([2,3,4]), dtype=tf.float32)
normal1

<tf.Variable 'Variable:0' shape=(2, 3, 4) dtype=float32, numpy=
array([[[-0.9665202 ,  0.04008941, -0.13938813,  1.1523879 ],
        [-0.48543945, -0.24574353,  0.07956366,  0.16446698],
        [ 1.7343488 ,  2.2561762 , -0.45879272, -0.15023293]],

       [[-2.705966  ,  0.47441712,  1.7625235 ,  0.7625122 ],
        [ 1.2060741 ,  0.5029623 , -0.38609213,  0.98861635],
        [ 0.1938119 , -0.43263164,  2.536628  ,  0.36939237]]],
      dtype=float32)>

In [6]:
tf.rank(normal1)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [7]:
tf.shape(normal1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4])>

In [8]:
normal2 = tf.random.normal([2,3,4], dtype=tf.float32)
normal2

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[-0.9004169 , -0.10074616, -1.9489676 ,  0.84165126],
        [ 0.8209429 , -1.3294547 ,  0.05401405, -1.2899635 ],
        [ 0.88021284,  0.12349848, -2.0988367 , -0.5440369 ]],

       [[-1.3140959 ,  0.42376646,  0.8028748 ,  1.0744394 ],
        [-0.45889887,  1.0159776 ,  0.67940545, -1.060875  ],
        [-0.14589563,  1.8054775 ,  0.01646128,  1.180608  ]]],
      dtype=float32)>

In [9]:
normal2.ndim

3

In [10]:
tf.shape(normal2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4])>