In [1]:
import tensorflow as tf

In [2]:
print ("TF Version: ", tf.__version__)

TF Version:  2.12.0


In [3]:
print ("Eager execution: ", tf.executing_eagerly())

Eager execution:  True


In [4]:
x = tf.constant(5, name='x')
y = tf.constant(8, name='y')

@tf.function
def calc_prod(x,y):
    z = 2*x + 3*y
    return z

result = calc_prod(x,y)
print('result = ',result)

result =  tf.Tensor(34, shape=(), dtype=int32)


#### @tf.function
This function makes inherit functions 'seems' like regular pyhton functions

In [8]:
### Generate a normalized tensor
normal1 = tf.Variable(tf.random.normal([2,3,4]), dtype=tf.float32)
normal1

<tf.Variable 'Variable:0' shape=(2, 3, 4) dtype=float32, numpy=
array([[[-0.31742722, -0.2886504 , -0.1920046 , -0.97027326],
        [ 0.38138053, -0.5355034 ,  0.59986055, -0.04730377],
        [-0.8536201 , -1.7210231 ,  0.9807632 , -1.1549584 ]],

       [[-1.403859  ,  0.94624585,  0.89666826, -0.58998954],
        [ 0.20633334,  1.4345778 ,  0.61396337,  1.7315279 ],
        [-0.57968634,  0.41780406, -0.28004223, -0.09791686]]],
      dtype=float32)>

In [9]:
tf.rank(normal1)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [10]:
tf.shape(normal1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4])>

In [15]:
normal2 = tf.random.normal([2,3,4], dtype=tf.float32)
normal2

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[ 2.3012574 ,  0.90126204,  0.63884187, -0.7658996 ],
        [ 1.606603  , -0.04825629, -0.2755805 , -0.47719854],
        [-1.1287494 ,  0.8443425 , -1.4322637 , -0.6838504 ]],

       [[-1.7456107 , -0.4739479 ,  1.4096808 ,  0.6593614 ],
        [-0.32434905, -0.11854175,  1.1209466 ,  1.5116463 ],
        [ 0.02716785, -0.337013  ,  0.10891726, -0.38723907]]],
      dtype=float32)>

In [16]:
normal2.ndim

3

In [18]:
tf.shape(normal2)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4])>